export function tenantPk(tenantId: string): string {
  return `TENANT#${tenantId}`;
}

export function configSk(): string {
  return "CONFIG";
}

export function sessionSk(sessionId: string): string {
  return `SESSION#${sessionId}`;
}

export function siteKeyGsi(siteKeyHash: string): {
  GSI1PK: string;
  GSI1SK: string;
} {
  return { GSI1PK: `SITEKEY#${siteKeyHash}`, GSI1SK: "TENANT" };
}

export function sessionPk(tenantId: string, sessionId: string): string {
  return `TENANT#${tenantId}#SESSION#${sessionId}`;
}

// A message sort key is `MSG#<ulid>`. The ULID (generated by the caller, which
// owns the `ulid` dependency) is lexicographically sortable and monotonic, so
// keys sort chronologically and never collide — even for same-millisecond
// writes. Keep this helper pure so `@platform/shared` stays dependency-free.
export function messageSk(id: string): string {
  return `MSG#${id}`;
}

export function productSk(productId: string): string {
  return `PRODUCT#${productId}`;
}

export function usageSk(month: string): string {
  return `USAGE#${month}`;
}

export function userPk(cognitoSub: string): string {
  return `USER#${cognitoSub}`;
}

export function profileSk(): string {
  return "PROFILE";
}

export function kbSk(id: string): string {
  return `KB#${id}`;
}

// Per-tenant snapshot of a page the widget was embedded on, keyed by a hash of
// the page URL so different pages of the same site are tracked independently.
// Lives under TENANT# so the existing LeadingKeys IAM boundary already covers it.
export function siteContentSk(urlHash: string): string {
  return `SITECONTENT#${urlHash}`;
}
